import { Component, OnInit, ViewChild, AfterViewInit } from '@angular/core';
import { MatPaginator, MatSort, MatTableDataSource } from '@angular/material';
import { SelectionModel } from '@angular/cdk/collections';

export interface prdData {
    id: number,
    name: string
}

export interface cusData {
    id: number,
    name: string
}

@Component({
    selector: 'ace-subsmgmt',
    templateUrl: './subsmgmt.component.html',
    styleUrls: ['./subsmgmt.component.less']
})
export class SubsmgmtComponent implements OnInit, AfterViewInit {
    @ViewChild('CustomersPaginator') cusPaginator: MatPaginator;
    @ViewChild('ProductsPaginator') prdPaginator: MatPaginator;

    customers: cusData[] = [
        { id: 1, name: "Agnes Dinges", products: [35, 40, 2, 31, 11, 19, 28] },
        { id: 2, name: "Alethia Gilham", products: [15, 32, 13, 27, 13, 16, 13, 38] },
        { id: 3, name: "Angelika Matte", products: [40, 19, 12, 31, 14] },
        { id: 4, name: "Annamae Bloss", products: [16, 11, 28, 5, 16, 38] },
        { id: 5, name: "Arlinda Conkling", products: [36, 36, 29, 30, 29, 27] },
        { id: 6, name: "Athena Savidge", products: [35, 38, 14] },
        { id: 7, name: "Billie Andrus", products: [14, 33, 39, 38] },
        { id: 8, name: "Bobbye Zeck", products: [8, 19] },
        { id: 9, name: "Booker Langevin", products: [28] },
        { id: 10, name: "Celeste Hannigan", products: [40, 20, 2, 14, 3] },
        { id: 11, name: "Charmain Palombo", products: [36, 39, 17, 15, 7] },
        { id: 12, name: "Cheri Catalan", products: [31, 6, 26, 16, 5, 22] },
        { id: 13, name: "Cherryl Craner", products: [4, 36, 9, 37] },
        { id: 14, name: "Chrissy Paiz", products: [2, 36, 22] },
        { id: 15, name: "Corine Holen", products: [6, 17, 5, 14, 20, 14] },
        { id: 16, name: "Cristine Dragoo", products: [1] },
        { id: 17, name: "Daina Scarpa", products: [32, 40] },
        { id: 18, name: "Daniela Giron", products: [15, 28, 22] },
        { id: 19, name: "Deetta Strayer", products: [22, 13, 5, 18, 25, 7, 31, 17, 6, 7] },
        { id: 20, name: "Deja Backhaus", products: [34, 9, 13, 30, 21] },
        { id: 21, name: "Dina Malcolm", products: [12, 29, 35, 32, 27, 25, 38, 12] },
        { id: 22, name: "Dominique Saiz", products: [32, 19, 24, 6, 7, 19, 24] },
        { id: 23, name: "Dorian Savala", products: [28, 32, 9, 8, 3, 24, 27, 13] },
        { id: 24, name: "Dorine Mazzone", products: [39, 7, 6] },
        { id: 25, name: "Drusilla Coots", products: [16, 27, 2, 35, 36, 20] },
        { id: 26, name: "Dwight Beaston", products: [33, 6, 8, 18, 6, 18] },
        { id: 27, name: "Elise Laboy", products: [31, 35, 8, 5, 13] },
        { id: 28, name: "Enedina Krohn", products: [14, 9, 10, 17, 40, 22] },
        { id: 29, name: "Eveline Stearn", products: [39, 27, 20, 6, 39] },
        { id: 30, name: "Fae Cusimano", products: [8, 33, 18, 23, 38, 18, 9] },
        { id: 31, name: "Fannie Witman", products: [36, 21, 9, 10] },
        { id: 32, name: "Gabriella Imler", products: [9, 29, 27, 15, 12, 15, 26, 22, 5, 4] },
        { id: 33, name: "Gerda Olive", products: [22, 24, 20] },
        { id: 34, name: "Glenda Salo", products: [40, 20, 7, 22, 8] },
        { id: 35, name: "Hollis Grady", products: [27, 34, 37, 30, 30] },
        { id: 36, name: "Hugh Martz", products: [11, 2, 24, 8, 15, 12, 38, 14, 23] },
        { id: 37, name: "Hyman Greenburg", products: [27, 5, 26, 34, 10, 17, 35, 35, 38] },
        { id: 38, name: "Ivette Zumwalt", products: [26, 35, 8, 23, 12, 8, 12, 32, 2, 27] },
        { id: 39, name: "Janie Gassett", products: [18, 6, 7, 14, 13, 36, 18, 12, 15, 8] },
        { id: 40, name: "Jasmin Dekker", products: [14, 20, 3] },
        { id: 41, name: "Jeane Eide", products: [12, 21, 35, 4] },
        { id: 42, name: "Jeanie Choiniere", products: [32, 15] },
        { id: 43, name: "Jeannette Spaeth", products: [40] },
        { id: 44, name: "Jerrie Glavin", products: [17, 28, 14, 23, 24, 2] },
        { id: 45, name: "John Crowther", products: [34, 38, 33] },
        { id: 46, name: "Jordon Townson", products: [18, 37, 4, 26, 13, 22, 19, 36, 40, 9] },
        { id: 47, name: "Josiah Feagins", products: [14, 33, 38, 33, 29, 37, 12, 36] },
        { id: 48, name: "Kaitlin Whipps", products: [13, 13, 28, 20, 34, 23, 16, 19, 17] },
        { id: 49, name: "Kate Dahlgren", products: [29, 25, 35, 32, 23, 10] },
        { id: 50, name: "Kelvin Hadsell", products: [25, 11, 32, 35, 34, 37, 5] },
        { id: 51, name: "Khalilah Withers", products: [1] },
        { id: 52, name: "Kimberlie Dombroski", products: [22, 34, 3, 12, 17, 11, 20, 26, 27] },
        { id: 53, name: "Leeanna Foutz", products: [35, 24, 14, 6, 16, 39, 20, 38, 25] },
        { id: 54, name: "Lenore Deady", products: [17, 6] },
        { id: 55, name: "Lianne Severance", products: [14, 3, 5, 22] },
        { id: 56, name: "Ling Fallen", products: [15, 37, 30, 2, 24, 34, 33, 3, 2, 4] },
        { id: 57, name: "Margarette Lavery", products: [20, 31, 1, 3, 31, 26, 1] },
        { id: 58, name: "Margherita Whisman", products: [7, 35] },
        { id: 59, name: "Melvina Gaytan", products: [34, 19, 29, 31, 12, 21, 37, 39, 1, 35] },
        { id: 60, name: "Michael Ly", products: [30, 25, 8, 21] },
        { id: 61, name: "Missy Wurtz", products: [16, 4] },
        { id: 62, name: "Mitzie Bliss", products: [31, 31, 21, 39, 10, 17, 6, 34, 1, 11] },
        { id: 63, name: "Modesto Nishida", products: [10, 33, 25, 24, 30, 2] },
        { id: 64, name: "Myra Palmore", products: [34, 1, 35, 18, 15, 23] },
        { id: 65, name: "Myrtice Dowler", products: [18, 7, 2, 2, 13, 7, 19, 36, 33, 28] },
        { id: 66, name: "Nickie Siegle", products: [10, 21] },
        { id: 67, name: "Nidia Jeter", products: [26, 16, 6, 35, 35, 8, 34, 12, 40, 29] },
        { id: 68, name: "Nubia Voges", products: [19, 6, 8] },
        { id: 69, name: "Octavia Cabello", products: [35, 24, 23, 11, 3, 30, 22] },
        { id: 70, name: "Pablo Forgey", products: [9, 2, 13, 37, 14] },
        { id: 71, name: "Patrica Whittier", products: [30, 9, 25, 15] },
        { id: 72, name: "Pearlie Sowell", products: [14, 26, 3, 39, 38, 28, 34] },
        { id: 73, name: "Pearline Saracino", products: [24, 40, 26, 19, 3, 6] },
        { id: 74, name: "Rachelle Sitz", products: [28, 18, 12, 12, 34, 7, 2, 24, 29] },
        { id: 75, name: "Ramiro Isreal", products: [19, 26, 11, 9, 5, 23, 9, 11] },
        { id: 76, name: "Randal Pipes", products: [34, 23, 37, 34, 18] },
        { id: 77, name: "Reyes Wile", products: [18, 20, 31, 7, 21, 15, 39, 18, 32] },
        { id: 78, name: "Rima Cromer", products: [12, 16, 5] },
        { id: 79, name: "Rosalina Vallance", products: [6, 9, 27] },
        { id: 80, name: "Roscoe Castaneda", products: [1, 12, 29, 5, 5, 5] },
        { id: 81, name: "Rossana Kerman", products: [4] },
        { id: 82, name: "Seth Songer", products: [30, 40, 27, 16, 26, 4, 6, 9, 33] },
        { id: 83, name: "Shad Kemper", products: [26, 2, 14, 12, 5, 11] },
        { id: 84, name: "Shala Marotta", products: [29, 23, 30, 19, 1, 4] },
        { id: 85, name: "Shanelle Riggin", products: [14, 9, 13, 13, 18, 22, 30, 28] },
        { id: 86, name: "Shantay Braga", products: [27, 28, 36, 37, 33] },
        { id: 87, name: "Shawanda Cayetano", products: [9, 30, 36, 1, 26, 27] },
        { id: 88, name: "Shela Jacinto", products: [34, 29] },
        { id: 89, name: "Shirl Bischof", products: [14, 38, 28] },
        { id: 90, name: "Sulema Restivo", products: [2, 17, 7, 1, 17, 23, 15] },
        { id: 91, name: "Sylvia Ellard", products: [30, 24, 25, 1, 11, 22] },
        { id: 92, name: "Tequila Bondy", products: [34, 13] },
        { id: 93, name: "Theresa Reichenbach", products: [29, 6, 19, 2, 30, 16, 31] },
        { id: 94, name: "Treva Pankow", products: [25, 13, 11, 17, 14, 2, 20, 39, 28] },
        { id: 95, name: "Vena Brundidge", products: [13, 9, 3, 19, 40, 33, 13, 34, 29] },
        { id: 96, name: "Vera Northup", products: [1, 34, 9, 29, 8, 18, 34, 38, 23] },
        { id: 97, name: "Wanita Ruzicka", products: [3, 9, 13, 16, 1, 11, 35, 2, 34] },
        { id: 98, name: "Willie Manriquez", products: [39, 33, 8] },
        { id: 99, name: "Windy Lossett", products: [32, 2, 9, 18, 17, 26, 40, 23] },
        { id: 100, name: "Yajaira Mazur", products: [30, 9, 24, 39, 9, 6, 19, 10] }
    ];

    products: prdData[] = [
        { "id": 1, "name": "Apache Records" },
        { "id": 2, "name": "Auragate" },
        { "id": 3, "name": "Cavestones" },
        { "id": 4, "name": "Cavologies" },
        { "id": 5, "name": "Cliffoods" },
        { "id": 6, "name": "Cliffway" },
        { "id": 7, "name": "Cruxolutions" },
        { "id": 8, "name": "Electrorks" },
        { "id": 9, "name": "Enigmotors" },
        { "id": 10, "name": "Forestway" },
        { "id": 11, "name": "Frostfire Navigations" },
        { "id": 12, "name": "Gale" },
        { "id": 13, "name": "Gnomehead" },
        { "id": 14, "name": "Gorillaworld" },
        { "id": 15, "name": "Grottoair" },
        { "id": 16, "name": "Hammermobile" },
        { "id": 17, "name": "Hurricanetworks" },
        { "id": 18, "name": "Imaginavigations" },
        { "id": 19, "name": "Leopardworks" },
        { "id": 20, "name": "Mars Corporation" },
        { "id": 21, "name": "Mazecurity" },
        { "id": 22, "name": "Mercury Coms" },
        { "id": 23, "name": "Moonlight Technologies" },
        { "id": 24, "name": "Nimbletainment" },
        { "id": 25, "name": "Oakbridge" },
        { "id": 26, "name": "Oysterwood" },
        { "id": 27, "name": "Peach Aviation" },
        { "id": 28, "name": "Pluto Foods" },
        { "id": 29, "name": "Pride Systems" },
        { "id": 30, "name": "Priductions" },
        { "id": 31, "name": "Pumpkin Microsystems" },
        { "id": 32, "name": "Questindustries" },
        { "id": 33, "name": "Questindustries" },
        { "id": 34, "name": "Sharkfin Entertainment" },
        { "id": 35, "name": "Smartland" },
        { "id": 36, "name": "Tulipnite" },
        { "id": 37, "name": "Tundracoustics" },
        { "id": 38, "name": "Twister" },
        { "id": 39, "name": "Wavigations" },
        { "id": 40, "name": "Witchystems" }
    ];

    // Not needed, but the cusData and prdData is built from this. Kept for reference
    subscriptions: any[] = [
        { "custid": 1, "custname": "Agnes Dinges", "prodid": 35, "prodname": "Smartland" },
        { "custid": 1, "custname": "Agnes Dinges", "prodid": 40, "prodname": "Witchystems" },
        { "custid": 1, "custname": "Agnes Dinges", "prodid": 2, "prodname": "Auragate" },
        { "custid": 1, "custname": "Agnes Dinges", "prodid": 31, "prodname": "Pumpkin Microsystems" },
        { "custid": 1, "custname": "Agnes Dinges", "prodid": 11, "prodname": "Frostfire Navigations" },
        { "custid": 1, "custname": "Agnes Dinges", "prodid": 19, "prodname": "Leopardworks" },
        { "custid": 1, "custname": "Agnes Dinges", "prodid": 28, "prodname": "Pluto Foods" },
        { "custid": 2, "custname": "Alethia Gilham", "prodid": 15, "prodname": "Grottoair" },
        { "custid": 2, "custname": "Alethia Gilham", "prodid": 32, "prodname": "Questindustries" },
        { "custid": 2, "custname": "Alethia Gilham", "prodid": 13, "prodname": "Gnomehead" },
        { "custid": 2, "custname": "Alethia Gilham", "prodid": 27, "prodname": "Peach Aviation" },
        { "custid": 2, "custname": "Alethia Gilham", "prodid": 16, "prodname": "Hammermobile" },
        { "custid": 2, "custname": "Alethia Gilham", "prodid": 38, "prodname": "Twister" },
        { "custid": 3, "custname": "Angelika Matte", "prodid": 40, "prodname": "Witchystems" },
        { "custid": 3, "custname": "Angelika Matte", "prodid": 19, "prodname": "Leopardworks" },
        { "custid": 3, "custname": "Angelika Matte", "prodid": 12, "prodname": "Gale" },
        { "custid": 3, "custname": "Angelika Matte", "prodid": 31, "prodname": "Pumpkin Microsystems" },
        { "custid": 3, "custname": "Angelika Matte", "prodid": 14, "prodname": "Gorillaworld" },
        { "custid": 4, "custname": "Annamae Bloss", "prodid": 16, "prodname": "Hammermobile" },
        { "custid": 4, "custname": "Annamae Bloss", "prodid": 11, "prodname": "Frostfire Navigations" },
        { "custid": 4, "custname": "Annamae Bloss", "prodid": 28, "prodname": "Pluto Foods" },
        { "custid": 4, "custname": "Annamae Bloss", "prodid": 5, "prodname": "Cliffoods" },
        { "custid": 4, "custname": "Annamae Bloss", "prodid": 38, "prodname": "Twister" },
        { "custid": 5, "custname": "Arlinda Conkling", "prodid": 36, "prodname": "Tulipnite" },
        { "custid": 5, "custname": "Arlinda Conkling", "prodid": 29, "prodname": "Pride Systems" },
        { "custid": 5, "custname": "Arlinda Conkling", "prodid": 30, "prodname": "Priductions" },
        { "custid": 5, "custname": "Arlinda Conkling", "prodid": 27, "prodname": "Peach Aviation" },
        { "custid": 6, "custname": "Athena Savidge", "prodid": 35, "prodname": "Smartland" },
        { "custid": 6, "custname": "Athena Savidge", "prodid": 38, "prodname": "Twister" },
        { "custid": 6, "custname": "Athena Savidge", "prodid": 14, "prodname": "Gorillaworld" },
        { "custid": 7, "custname": "Billie Andrus", "prodid": 14, "prodname": "Gorillaworld" },
        { "custid": 7, "custname": "Billie Andrus", "prodid": 33, "prodname": "Questindustries" },
        { "custid": 7, "custname": "Billie Andrus", "prodid": 39, "prodname": "Wavigations" },
        { "custid": 7, "custname": "Billie Andrus", "prodid": 38, "prodname": "Twister" },
        { "custid": 8, "custname": "Bobbye Zeck", "prodid": 8, "prodname": "Electrorks" },
        { "custid": 8, "custname": "Bobbye Zeck", "prodid": 19, "prodname": "Leopardworks" },
        { "custid": 9, "custname": "Booker Langevin", "prodid": 28, "prodname": "Pluto Foods" },
        { "custid": 10, "custname": "Celeste Hannigan", "prodid": 40, "prodname": "Witchystems" },
        { "custid": 10, "custname": "Celeste Hannigan", "prodid": 20, "prodname": "Mars Corporation" },
        { "custid": 10, "custname": "Celeste Hannigan", "prodid": 2, "prodname": "Auragate" },
        { "custid": 10, "custname": "Celeste Hannigan", "prodid": 14, "prodname": "Gorillaworld" },
        { "custid": 10, "custname": "Celeste Hannigan", "prodid": 3, "prodname": "Cavestones" },
        { "custid": 11, "custname": "Charmain Palombo", "prodid": 36, "prodname": "Tulipnite" },
        { "custid": 11, "custname": "Charmain Palombo", "prodid": 39, "prodname": "Wavigations" },
        { "custid": 11, "custname": "Charmain Palombo", "prodid": 17, "prodname": "Hurricanetworks" },
        { "custid": 11, "custname": "Charmain Palombo", "prodid": 15, "prodname": "Grottoair" },
        { "custid": 11, "custname": "Charmain Palombo", "prodid": 7, "prodname": "Cruxolutions" },
        { "custid": 12, "custname": "Cheri Catalan", "prodid": 31, "prodname": "Pumpkin Microsystems" },
        { "custid": 12, "custname": "Cheri Catalan", "prodid": 6, "prodname": "Cliffway" },
        { "custid": 12, "custname": "Cheri Catalan", "prodid": 26, "prodname": "Oysterwood" },
        { "custid": 12, "custname": "Cheri Catalan", "prodid": 16, "prodname": "Hammermobile" },
        { "custid": 12, "custname": "Cheri Catalan", "prodid": 5, "prodname": "Cliffoods" },
        { "custid": 12, "custname": "Cheri Catalan", "prodid": 22, "prodname": "Mercury Coms" },
        { "custid": 13, "custname": "Cherryl Craner", "prodid": 4, "prodname": "Cavologies" },
        { "custid": 13, "custname": "Cherryl Craner", "prodid": 36, "prodname": "Tulipnite" },
        { "custid": 13, "custname": "Cherryl Craner", "prodid": 9, "prodname": "Enigmotors" },
        { "custid": 13, "custname": "Cherryl Craner", "prodid": 37, "prodname": "Tundracoustics" },
        { "custid": 14, "custname": "Chrissy Paiz", "prodid": 2, "prodname": "Auragate" },
        { "custid": 14, "custname": "Chrissy Paiz", "prodid": 36, "prodname": "Tulipnite" },
        { "custid": 14, "custname": "Chrissy Paiz", "prodid": 22, "prodname": "Mercury Coms" },
        { "custid": 15, "custname": "Corine Holen", "prodid": 6, "prodname": "Cliffway" },
        { "custid": 15, "custname": "Corine Holen", "prodid": 17, "prodname": "Hurricanetworks" },
        { "custid": 15, "custname": "Corine Holen", "prodid": 5, "prodname": "Cliffoods" },
        { "custid": 15, "custname": "Corine Holen", "prodid": 14, "prodname": "Gorillaworld" },
        { "custid": 15, "custname": "Corine Holen", "prodid": 20, "prodname": "Mars Corporation" },
        { "custid": 16, "custname": "Cristine Dragoo", "prodid": 1, "prodname": "Apache Records" },
        { "custid": 17, "custname": "Daina Scarpa", "prodid": 32, "prodname": "Questindustries" },
        { "custid": 17, "custname": "Daina Scarpa", "prodid": 40, "prodname": "Witchystems" },
        { "custid": 18, "custname": "Daniela Giron", "prodid": 15, "prodname": "Grottoair" },
        { "custid": 18, "custname": "Daniela Giron", "prodid": 28, "prodname": "Pluto Foods" },
        { "custid": 18, "custname": "Daniela Giron", "prodid": 22, "prodname": "Mercury Coms" },
        { "custid": 19, "custname": "Deetta Strayer", "prodid": 22, "prodname": "Mercury Coms" },
        { "custid": 19, "custname": "Deetta Strayer", "prodid": 13, "prodname": "Gnomehead" },
        { "custid": 19, "custname": "Deetta Strayer", "prodid": 5, "prodname": "Cliffoods" },
        { "custid": 19, "custname": "Deetta Strayer", "prodid": 18, "prodname": "Imaginavigations" },
        { "custid": 19, "custname": "Deetta Strayer", "prodid": 25, "prodname": "Oakbridge" },
        { "custid": 19, "custname": "Deetta Strayer", "prodid": 7, "prodname": "Cruxolutions" },
        { "custid": 19, "custname": "Deetta Strayer", "prodid": 31, "prodname": "Pumpkin Microsystems" },
        { "custid": 19, "custname": "Deetta Strayer", "prodid": 17, "prodname": "Hurricanetworks" },
        { "custid": 19, "custname": "Deetta Strayer", "prodid": 6, "prodname": "Cliffway" },
        { "custid": 20, "custname": "Deja Backhaus", "prodid": 34, "prodname": "Sharkfin Entertainment" },
        { "custid": 20, "custname": "Deja Backhaus", "prodid": 9, "prodname": "Enigmotors" },
        { "custid": 20, "custname": "Deja Backhaus", "prodid": 13, "prodname": "Gnomehead" },
        { "custid": 20, "custname": "Deja Backhaus", "prodid": 30, "prodname": "Priductions" },
        { "custid": 20, "custname": "Deja Backhaus", "prodid": 21, "prodname": "Mazecurity" },
        { "custid": 21, "custname": "Dina Malcolm", "prodid": 12, "prodname": "Gale" },
        { "custid": 21, "custname": "Dina Malcolm", "prodid": 29, "prodname": "Pride Systems" },
        { "custid": 21, "custname": "Dina Malcolm", "prodid": 35, "prodname": "Smartland" },
        { "custid": 21, "custname": "Dina Malcolm", "prodid": 32, "prodname": "Questindustries" },
        { "custid": 21, "custname": "Dina Malcolm", "prodid": 27, "prodname": "Peach Aviation" },
        { "custid": 21, "custname": "Dina Malcolm", "prodid": 25, "prodname": "Oakbridge" },
        { "custid": 21, "custname": "Dina Malcolm", "prodid": 38, "prodname": "Twister" },
        { "custid": 22, "custname": "Dominique Saiz", "prodid": 32, "prodname": "Questindustries" },
        { "custid": 22, "custname": "Dominique Saiz", "prodid": 19, "prodname": "Leopardworks" },
        { "custid": 22, "custname": "Dominique Saiz", "prodid": 24, "prodname": "Nimbletainment" },
        { "custid": 22, "custname": "Dominique Saiz", "prodid": 6, "prodname": "Cliffway" },
        { "custid": 22, "custname": "Dominique Saiz", "prodid": 7, "prodname": "Cruxolutions" },
        { "custid": 23, "custname": "Dorian Savala", "prodid": 28, "prodname": "Pluto Foods" },
        { "custid": 23, "custname": "Dorian Savala", "prodid": 32, "prodname": "Questindustries" },
        { "custid": 23, "custname": "Dorian Savala", "prodid": 9, "prodname": "Enigmotors" },
        { "custid": 23, "custname": "Dorian Savala", "prodid": 8, "prodname": "Electrorks" },
        { "custid": 23, "custname": "Dorian Savala", "prodid": 3, "prodname": "Cavestones" },
        { "custid": 23, "custname": "Dorian Savala", "prodid": 24, "prodname": "Nimbletainment" },
        { "custid": 23, "custname": "Dorian Savala", "prodid": 27, "prodname": "Peach Aviation" },
        { "custid": 23, "custname": "Dorian Savala", "prodid": 13, "prodname": "Gnomehead" },
        { "custid": 24, "custname": "Dorine Mazzone", "prodid": 39, "prodname": "Wavigations" },
        { "custid": 24, "custname": "Dorine Mazzone", "prodid": 7, "prodname": "Cruxolutions" },
        { "custid": 24, "custname": "Dorine Mazzone", "prodid": 6, "prodname": "Cliffway" },
        { "custid": 25, "custname": "Drusilla Coots", "prodid": 16, "prodname": "Hammermobile" },
        { "custid": 25, "custname": "Drusilla Coots", "prodid": 27, "prodname": "Peach Aviation" },
        { "custid": 25, "custname": "Drusilla Coots", "prodid": 2, "prodname": "Auragate" },
        { "custid": 25, "custname": "Drusilla Coots", "prodid": 35, "prodname": "Smartland" },
        { "custid": 25, "custname": "Drusilla Coots", "prodid": 36, "prodname": "Tulipnite" },
        { "custid": 25, "custname": "Drusilla Coots", "prodid": 20, "prodname": "Mars Corporation" },
        { "custid": 26, "custname": "Dwight Beaston", "prodid": 33, "prodname": "Questindustries" },
        { "custid": 26, "custname": "Dwight Beaston", "prodid": 6, "prodname": "Cliffway" },
        { "custid": 26, "custname": "Dwight Beaston", "prodid": 8, "prodname": "Electrorks" },
        { "custid": 26, "custname": "Dwight Beaston", "prodid": 18, "prodname": "Imaginavigations" },
        { "custid": 27, "custname": "Elise Laboy", "prodid": 31, "prodname": "Pumpkin Microsystems" },
        { "custid": 27, "custname": "Elise Laboy", "prodid": 35, "prodname": "Smartland" },
        { "custid": 27, "custname": "Elise Laboy", "prodid": 8, "prodname": "Electrorks" },
        { "custid": 27, "custname": "Elise Laboy", "prodid": 5, "prodname": "Cliffoods" },
        { "custid": 27, "custname": "Elise Laboy", "prodid": 13, "prodname": "Gnomehead" },
        { "custid": 28, "custname": "Enedina Krohn", "prodid": 14, "prodname": "Gorillaworld" },
        { "custid": 28, "custname": "Enedina Krohn", "prodid": 9, "prodname": "Enigmotors" },
        { "custid": 28, "custname": "Enedina Krohn", "prodid": 10, "prodname": "Forestway" },
        { "custid": 28, "custname": "Enedina Krohn", "prodid": 17, "prodname": "Hurricanetworks" },
        { "custid": 28, "custname": "Enedina Krohn", "prodid": 40, "prodname": "Witchystems" },
        { "custid": 28, "custname": "Enedina Krohn", "prodid": 22, "prodname": "Mercury Coms" },
        { "custid": 29, "custname": "Eveline Stearn", "prodid": 39, "prodname": "Wavigations" },
        { "custid": 29, "custname": "Eveline Stearn", "prodid": 27, "prodname": "Peach Aviation" },
        { "custid": 29, "custname": "Eveline Stearn", "prodid": 20, "prodname": "Mars Corporation" },
        { "custid": 29, "custname": "Eveline Stearn", "prodid": 6, "prodname": "Cliffway" },
        { "custid": 30, "custname": "Fae Cusimano", "prodid": 8, "prodname": "Electrorks" },
        { "custid": 30, "custname": "Fae Cusimano", "prodid": 33, "prodname": "Questindustries" },
        { "custid": 30, "custname": "Fae Cusimano", "prodid": 18, "prodname": "Imaginavigations" },
        { "custid": 30, "custname": "Fae Cusimano", "prodid": 23, "prodname": "Moonlight Technologies" },
        { "custid": 30, "custname": "Fae Cusimano", "prodid": 38, "prodname": "Twister" },
        { "custid": 30, "custname": "Fae Cusimano", "prodid": 9, "prodname": "Enigmotors" },
        { "custid": 31, "custname": "Fannie Witman", "prodid": 36, "prodname": "Tulipnite" },
        { "custid": 31, "custname": "Fannie Witman", "prodid": 21, "prodname": "Mazecurity" },
        { "custid": 31, "custname": "Fannie Witman", "prodid": 9, "prodname": "Enigmotors" },
        { "custid": 31, "custname": "Fannie Witman", "prodid": 10, "prodname": "Forestway" },
        { "custid": 32, "custname": "Gabriella Imler", "prodid": 9, "prodname": "Enigmotors" },
        { "custid": 32, "custname": "Gabriella Imler", "prodid": 29, "prodname": "Pride Systems" },
        { "custid": 32, "custname": "Gabriella Imler", "prodid": 27, "prodname": "Peach Aviation" },
        { "custid": 32, "custname": "Gabriella Imler", "prodid": 15, "prodname": "Grottoair" },
        { "custid": 32, "custname": "Gabriella Imler", "prodid": 12, "prodname": "Gale" },
        { "custid": 32, "custname": "Gabriella Imler", "prodid": 26, "prodname": "Oysterwood" },
        { "custid": 32, "custname": "Gabriella Imler", "prodid": 22, "prodname": "Mercury Coms" },
        { "custid": 32, "custname": "Gabriella Imler", "prodid": 5, "prodname": "Cliffoods" },
        { "custid": 32, "custname": "Gabriella Imler", "prodid": 4, "prodname": "Cavologies" },
        { "custid": 33, "custname": "Gerda Olive", "prodid": 22, "prodname": "Mercury Coms" },
        { "custid": 33, "custname": "Gerda Olive", "prodid": 24, "prodname": "Nimbletainment" },
        { "custid": 33, "custname": "Gerda Olive", "prodid": 20, "prodname": "Mars Corporation" },
        { "custid": 34, "custname": "Glenda Salo", "prodid": 40, "prodname": "Witchystems" },
        { "custid": 34, "custname": "Glenda Salo", "prodid": 20, "prodname": "Mars Corporation" },
        { "custid": 34, "custname": "Glenda Salo", "prodid": 7, "prodname": "Cruxolutions" },
        { "custid": 34, "custname": "Glenda Salo", "prodid": 22, "prodname": "Mercury Coms" },
        { "custid": 34, "custname": "Glenda Salo", "prodid": 8, "prodname": "Electrorks" },
        { "custid": 35, "custname": "Hollis Grady", "prodid": 27, "prodname": "Peach Aviation" },
        { "custid": 35, "custname": "Hollis Grady", "prodid": 34, "prodname": "Sharkfin Entertainment" },
        { "custid": 35, "custname": "Hollis Grady", "prodid": 37, "prodname": "Tundracoustics" },
        { "custid": 35, "custname": "Hollis Grady", "prodid": 30, "prodname": "Priductions" },
        { "custid": 36, "custname": "Hugh Martz", "prodid": 11, "prodname": "Frostfire Navigations" },
        { "custid": 36, "custname": "Hugh Martz", "prodid": 2, "prodname": "Auragate" },
        { "custid": 36, "custname": "Hugh Martz", "prodid": 24, "prodname": "Nimbletainment" },
        { "custid": 36, "custname": "Hugh Martz", "prodid": 8, "prodname": "Electrorks" },
        { "custid": 36, "custname": "Hugh Martz", "prodid": 15, "prodname": "Grottoair" },
        { "custid": 36, "custname": "Hugh Martz", "prodid": 12, "prodname": "Gale" },
        { "custid": 36, "custname": "Hugh Martz", "prodid": 38, "prodname": "Twister" },
        { "custid": 36, "custname": "Hugh Martz", "prodid": 14, "prodname": "Gorillaworld" },
        { "custid": 36, "custname": "Hugh Martz", "prodid": 23, "prodname": "Moonlight Technologies" },
        { "custid": 37, "custname": "Hyman Greenburg", "prodid": 27, "prodname": "Peach Aviation" },
        { "custid": 37, "custname": "Hyman Greenburg", "prodid": 5, "prodname": "Cliffoods" },
        { "custid": 37, "custname": "Hyman Greenburg", "prodid": 26, "prodname": "Oysterwood" },
        { "custid": 37, "custname": "Hyman Greenburg", "prodid": 34, "prodname": "Sharkfin Entertainment" },
        { "custid": 37, "custname": "Hyman Greenburg", "prodid": 10, "prodname": "Forestway" },
        { "custid": 37, "custname": "Hyman Greenburg", "prodid": 17, "prodname": "Hurricanetworks" },
        { "custid": 37, "custname": "Hyman Greenburg", "prodid": 35, "prodname": "Smartland" },
        { "custid": 37, "custname": "Hyman Greenburg", "prodid": 38, "prodname": "Twister" },
        { "custid": 38, "custname": "Ivette Zumwalt", "prodid": 26, "prodname": "Oysterwood" },
        { "custid": 38, "custname": "Ivette Zumwalt", "prodid": 35, "prodname": "Smartland" },
        { "custid": 38, "custname": "Ivette Zumwalt", "prodid": 8, "prodname": "Electrorks" },
        { "custid": 38, "custname": "Ivette Zumwalt", "prodid": 23, "prodname": "Moonlight Technologies" },
        { "custid": 38, "custname": "Ivette Zumwalt", "prodid": 12, "prodname": "Gale" },
        { "custid": 38, "custname": "Ivette Zumwalt", "prodid": 32, "prodname": "Questindustries" },
        { "custid": 38, "custname": "Ivette Zumwalt", "prodid": 2, "prodname": "Auragate" },
        { "custid": 38, "custname": "Ivette Zumwalt", "prodid": 27, "prodname": "Peach Aviation" },
        { "custid": 39, "custname": "Janie Gassett", "prodid": 18, "prodname": "Imaginavigations" },
        { "custid": 39, "custname": "Janie Gassett", "prodid": 6, "prodname": "Cliffway" },
        { "custid": 39, "custname": "Janie Gassett", "prodid": 7, "prodname": "Cruxolutions" },
        { "custid": 39, "custname": "Janie Gassett", "prodid": 14, "prodname": "Gorillaworld" },
        { "custid": 39, "custname": "Janie Gassett", "prodid": 13, "prodname": "Gnomehead" },
        { "custid": 39, "custname": "Janie Gassett", "prodid": 36, "prodname": "Tulipnite" },
        { "custid": 39, "custname": "Janie Gassett", "prodid": 12, "prodname": "Gale" },
        { "custid": 39, "custname": "Janie Gassett", "prodid": 15, "prodname": "Grottoair" },
        { "custid": 39, "custname": "Janie Gassett", "prodid": 8, "prodname": "Electrorks" },
        { "custid": 40, "custname": "Jasmin Dekker", "prodid": 14, "prodname": "Gorillaworld" },
        { "custid": 40, "custname": "Jasmin Dekker", "prodid": 20, "prodname": "Mars Corporation" },
        { "custid": 40, "custname": "Jasmin Dekker", "prodid": 3, "prodname": "Cavestones" },
        { "custid": 41, "custname": "Jeane Eide", "prodid": 12, "prodname": "Gale" },
        { "custid": 41, "custname": "Jeane Eide", "prodid": 21, "prodname": "Mazecurity" },
        { "custid": 41, "custname": "Jeane Eide", "prodid": 35, "prodname": "Smartland" },
        { "custid": 41, "custname": "Jeane Eide", "prodid": 4, "prodname": "Cavologies" },
        { "custid": 42, "custname": "Jeanie Choiniere", "prodid": 32, "prodname": "Questindustries" },
        { "custid": 42, "custname": "Jeanie Choiniere", "prodid": 15, "prodname": "Grottoair" },
        { "custid": 43, "custname": "Jeannette Spaeth", "prodid": 40, "prodname": "Witchystems" },
        { "custid": 44, "custname": "Jerrie Glavin", "prodid": 17, "prodname": "Hurricanetworks" },
        { "custid": 44, "custname": "Jerrie Glavin", "prodid": 28, "prodname": "Pluto Foods" },
        { "custid": 44, "custname": "Jerrie Glavin", "prodid": 14, "prodname": "Gorillaworld" },
        { "custid": 44, "custname": "Jerrie Glavin", "prodid": 23, "prodname": "Moonlight Technologies" },
        { "custid": 44, "custname": "Jerrie Glavin", "prodid": 24, "prodname": "Nimbletainment" },
        { "custid": 44, "custname": "Jerrie Glavin", "prodid": 2, "prodname": "Auragate" },
        { "custid": 45, "custname": "John Crowther", "prodid": 34, "prodname": "Sharkfin Entertainment" },
        { "custid": 45, "custname": "John Crowther", "prodid": 38, "prodname": "Twister" },
        { "custid": 45, "custname": "John Crowther", "prodid": 33, "prodname": "Questindustries" },
        { "custid": 46, "custname": "Jordon Townson", "prodid": 18, "prodname": "Imaginavigations" },
        { "custid": 46, "custname": "Jordon Townson", "prodid": 37, "prodname": "Tundracoustics" },
        { "custid": 46, "custname": "Jordon Townson", "prodid": 4, "prodname": "Cavologies" },
        { "custid": 46, "custname": "Jordon Townson", "prodid": 26, "prodname": "Oysterwood" },
        { "custid": 46, "custname": "Jordon Townson", "prodid": 13, "prodname": "Gnomehead" },
        { "custid": 46, "custname": "Jordon Townson", "prodid": 22, "prodname": "Mercury Coms" },
        { "custid": 46, "custname": "Jordon Townson", "prodid": 19, "prodname": "Leopardworks" },
        { "custid": 46, "custname": "Jordon Townson", "prodid": 36, "prodname": "Tulipnite" },
        { "custid": 46, "custname": "Jordon Townson", "prodid": 40, "prodname": "Witchystems" },
        { "custid": 46, "custname": "Jordon Townson", "prodid": 9, "prodname": "Enigmotors" },
        { "custid": 47, "custname": "Josiah Feagins", "prodid": 14, "prodname": "Gorillaworld" },
        { "custid": 47, "custname": "Josiah Feagins", "prodid": 33, "prodname": "Questindustries" },
        { "custid": 47, "custname": "Josiah Feagins", "prodid": 38, "prodname": "Twister" },
        { "custid": 47, "custname": "Josiah Feagins", "prodid": 29, "prodname": "Pride Systems" },
        { "custid": 47, "custname": "Josiah Feagins", "prodid": 37, "prodname": "Tundracoustics" },
        { "custid": 47, "custname": "Josiah Feagins", "prodid": 12, "prodname": "Gale" },
        { "custid": 47, "custname": "Josiah Feagins", "prodid": 36, "prodname": "Tulipnite" },
        { "custid": 48, "custname": "Kaitlin Whipps", "prodid": 13, "prodname": "Gnomehead" },
        { "custid": 48, "custname": "Kaitlin Whipps", "prodid": 28, "prodname": "Pluto Foods" },
        { "custid": 48, "custname": "Kaitlin Whipps", "prodid": 20, "prodname": "Mars Corporation" },
        { "custid": 48, "custname": "Kaitlin Whipps", "prodid": 34, "prodname": "Sharkfin Entertainment" },
        { "custid": 48, "custname": "Kaitlin Whipps", "prodid": 23, "prodname": "Moonlight Technologies" },
        { "custid": 48, "custname": "Kaitlin Whipps", "prodid": 16, "prodname": "Hammermobile" },
        { "custid": 48, "custname": "Kaitlin Whipps", "prodid": 19, "prodname": "Leopardworks" },
        { "custid": 48, "custname": "Kaitlin Whipps", "prodid": 17, "prodname": "Hurricanetworks" },
        { "custid": 49, "custname": "Kate Dahlgren", "prodid": 29, "prodname": "Pride Systems" },
        { "custid": 49, "custname": "Kate Dahlgren", "prodid": 25, "prodname": "Oakbridge" },
        { "custid": 49, "custname": "Kate Dahlgren", "prodid": 35, "prodname": "Smartland" },
        { "custid": 49, "custname": "Kate Dahlgren", "prodid": 32, "prodname": "Questindustries" },
        { "custid": 49, "custname": "Kate Dahlgren", "prodid": 23, "prodname": "Moonlight Technologies" },
        { "custid": 49, "custname": "Kate Dahlgren", "prodid": 10, "prodname": "Forestway" },
        { "custid": 50, "custname": "Kelvin Hadsell", "prodid": 25, "prodname": "Oakbridge" },
        { "custid": 50, "custname": "Kelvin Hadsell", "prodid": 11, "prodname": "Frostfire Navigations" },
        { "custid": 50, "custname": "Kelvin Hadsell", "prodid": 32, "prodname": "Questindustries" },
        { "custid": 50, "custname": "Kelvin Hadsell", "prodid": 35, "prodname": "Smartland" },
        { "custid": 50, "custname": "Kelvin Hadsell", "prodid": 34, "prodname": "Sharkfin Entertainment" },
        { "custid": 50, "custname": "Kelvin Hadsell", "prodid": 37, "prodname": "Tundracoustics" },
        { "custid": 50, "custname": "Kelvin Hadsell", "prodid": 5, "prodname": "Cliffoods" },
        { "custid": 51, "custname": "Khalilah Withers", "prodid": 1, "prodname": "Apache Records" },
        { "custid": 52, "custname": "Kimberlie Dombroski", "prodid": 22, "prodname": "Mercury Coms" },
        { "custid": 52, "custname": "Kimberlie Dombroski", "prodid": 34, "prodname": "Sharkfin Entertainment" },
        { "custid": 52, "custname": "Kimberlie Dombroski", "prodid": 3, "prodname": "Cavestones" },
        { "custid": 52, "custname": "Kimberlie Dombroski", "prodid": 12, "prodname": "Gale" },
        { "custid": 52, "custname": "Kimberlie Dombroski", "prodid": 17, "prodname": "Hurricanetworks" },
        { "custid": 52, "custname": "Kimberlie Dombroski", "prodid": 11, "prodname": "Frostfire Navigations" },
        { "custid": 52, "custname": "Kimberlie Dombroski", "prodid": 20, "prodname": "Mars Corporation" },
        { "custid": 52, "custname": "Kimberlie Dombroski", "prodid": 26, "prodname": "Oysterwood" },
        { "custid": 52, "custname": "Kimberlie Dombroski", "prodid": 27, "prodname": "Peach Aviation" },
        { "custid": 53, "custname": "Leeanna Foutz", "prodid": 35, "prodname": "Smartland" },
        { "custid": 53, "custname": "Leeanna Foutz", "prodid": 24, "prodname": "Nimbletainment" },
        { "custid": 53, "custname": "Leeanna Foutz", "prodid": 14, "prodname": "Gorillaworld" },
        { "custid": 53, "custname": "Leeanna Foutz", "prodid": 6, "prodname": "Cliffway" },
        { "custid": 53, "custname": "Leeanna Foutz", "prodid": 16, "prodname": "Hammermobile" },
        { "custid": 53, "custname": "Leeanna Foutz", "prodid": 39, "prodname": "Wavigations" },
        { "custid": 53, "custname": "Leeanna Foutz", "prodid": 20, "prodname": "Mars Corporation" },
        { "custid": 53, "custname": "Leeanna Foutz", "prodid": 38, "prodname": "Twister" },
        { "custid": 53, "custname": "Leeanna Foutz", "prodid": 25, "prodname": "Oakbridge" },
        { "custid": 54, "custname": "Lenore Deady", "prodid": 17, "prodname": "Hurricanetworks" },
        { "custid": 54, "custname": "Lenore Deady", "prodid": 6, "prodname": "Cliffway" },
        { "custid": 55, "custname": "Lianne Severance", "prodid": 14, "prodname": "Gorillaworld" },
        { "custid": 55, "custname": "Lianne Severance", "prodid": 3, "prodname": "Cavestones" },
        { "custid": 55, "custname": "Lianne Severance", "prodid": 5, "prodname": "Cliffoods" },
        { "custid": 55, "custname": "Lianne Severance", "prodid": 22, "prodname": "Mercury Coms" },
        { "custid": 56, "custname": "Ling Fallen", "prodid": 15, "prodname": "Grottoair" },
        { "custid": 56, "custname": "Ling Fallen", "prodid": 37, "prodname": "Tundracoustics" },
        { "custid": 56, "custname": "Ling Fallen", "prodid": 30, "prodname": "Priductions" },
        { "custid": 56, "custname": "Ling Fallen", "prodid": 2, "prodname": "Auragate" },
        { "custid": 56, "custname": "Ling Fallen", "prodid": 24, "prodname": "Nimbletainment" },
        { "custid": 56, "custname": "Ling Fallen", "prodid": 34, "prodname": "Sharkfin Entertainment" },
        { "custid": 56, "custname": "Ling Fallen", "prodid": 33, "prodname": "Questindustries" },
        { "custid": 56, "custname": "Ling Fallen", "prodid": 3, "prodname": "Cavestones" },
        { "custid": 56, "custname": "Ling Fallen", "prodid": 4, "prodname": "Cavologies" },
        { "custid": 57, "custname": "Margarette Lavery", "prodid": 20, "prodname": "Mars Corporation" },
        { "custid": 57, "custname": "Margarette Lavery", "prodid": 31, "prodname": "Pumpkin Microsystems" },
        { "custid": 57, "custname": "Margarette Lavery", "prodid": 1, "prodname": "Apache Records" },
        { "custid": 57, "custname": "Margarette Lavery", "prodid": 3, "prodname": "Cavestones" },
        { "custid": 57, "custname": "Margarette Lavery", "prodid": 26, "prodname": "Oysterwood" },
        { "custid": 58, "custname": "Margherita Whisman", "prodid": 7, "prodname": "Cruxolutions" },
        { "custid": 58, "custname": "Margherita Whisman", "prodid": 35, "prodname": "Smartland" },
        { "custid": 59, "custname": "Melvina Gaytan", "prodid": 34, "prodname": "Sharkfin Entertainment" },
        { "custid": 59, "custname": "Melvina Gaytan", "prodid": 19, "prodname": "Leopardworks" },
        { "custid": 59, "custname": "Melvina Gaytan", "prodid": 29, "prodname": "Pride Systems" },
        { "custid": 59, "custname": "Melvina Gaytan", "prodid": 31, "prodname": "Pumpkin Microsystems" },
        { "custid": 59, "custname": "Melvina Gaytan", "prodid": 12, "prodname": "Gale" },
        { "custid": 59, "custname": "Melvina Gaytan", "prodid": 21, "prodname": "Mazecurity" },
        { "custid": 59, "custname": "Melvina Gaytan", "prodid": 37, "prodname": "Tundracoustics" },
        { "custid": 59, "custname": "Melvina Gaytan", "prodid": 39, "prodname": "Wavigations" },
        { "custid": 59, "custname": "Melvina Gaytan", "prodid": 1, "prodname": "Apache Records" },
        { "custid": 59, "custname": "Melvina Gaytan", "prodid": 35, "prodname": "Smartland" },
        { "custid": 60, "custname": "Michael Ly", "prodid": 30, "prodname": "Priductions" },
        { "custid": 60, "custname": "Michael Ly", "prodid": 25, "prodname": "Oakbridge" },
        { "custid": 60, "custname": "Michael Ly", "prodid": 8, "prodname": "Electrorks" },
        { "custid": 60, "custname": "Michael Ly", "prodid": 21, "prodname": "Mazecurity" },
        { "custid": 61, "custname": "Missy Wurtz", "prodid": 16, "prodname": "Hammermobile" },
        { "custid": 61, "custname": "Missy Wurtz", "prodid": 4, "prodname": "Cavologies" },
        { "custid": 62, "custname": "Mitzie Bliss", "prodid": 31, "prodname": "Pumpkin Microsystems" },
        { "custid": 62, "custname": "Mitzie Bliss", "prodid": 21, "prodname": "Mazecurity" },
        { "custid": 62, "custname": "Mitzie Bliss", "prodid": 39, "prodname": "Wavigations" },
        { "custid": 62, "custname": "Mitzie Bliss", "prodid": 10, "prodname": "Forestway" },
        { "custid": 62, "custname": "Mitzie Bliss", "prodid": 17, "prodname": "Hurricanetworks" },
        { "custid": 62, "custname": "Mitzie Bliss", "prodid": 6, "prodname": "Cliffway" },
        { "custid": 62, "custname": "Mitzie Bliss", "prodid": 34, "prodname": "Sharkfin Entertainment" },
        { "custid": 62, "custname": "Mitzie Bliss", "prodid": 1, "prodname": "Apache Records" },
        { "custid": 62, "custname": "Mitzie Bliss", "prodid": 11, "prodname": "Frostfire Navigations" },
        { "custid": 63, "custname": "Modesto Nishida", "prodid": 10, "prodname": "Forestway" },
        { "custid": 63, "custname": "Modesto Nishida", "prodid": 33, "prodname": "Questindustries" },
        { "custid": 63, "custname": "Modesto Nishida", "prodid": 25, "prodname": "Oakbridge" },
        { "custid": 63, "custname": "Modesto Nishida", "prodid": 24, "prodname": "Nimbletainment" },
        { "custid": 63, "custname": "Modesto Nishida", "prodid": 30, "prodname": "Priductions" },
        { "custid": 63, "custname": "Modesto Nishida", "prodid": 2, "prodname": "Auragate" },
        { "custid": 64, "custname": "Myra Palmore", "prodid": 34, "prodname": "Sharkfin Entertainment" },
        { "custid": 64, "custname": "Myra Palmore", "prodid": 1, "prodname": "Apache Records" },
        { "custid": 64, "custname": "Myra Palmore", "prodid": 35, "prodname": "Smartland" },
        { "custid": 64, "custname": "Myra Palmore", "prodid": 18, "prodname": "Imaginavigations" },
        { "custid": 64, "custname": "Myra Palmore", "prodid": 15, "prodname": "Grottoair" },
        { "custid": 64, "custname": "Myra Palmore", "prodid": 23, "prodname": "Moonlight Technologies" },
        { "custid": 65, "custname": "Myrtice Dowler", "prodid": 18, "prodname": "Imaginavigations" },
        { "custid": 65, "custname": "Myrtice Dowler", "prodid": 7, "prodname": "Cruxolutions" },
        { "custid": 65, "custname": "Myrtice Dowler", "prodid": 2, "prodname": "Auragate" },
        { "custid": 65, "custname": "Myrtice Dowler", "prodid": 13, "prodname": "Gnomehead" },
        { "custid": 65, "custname": "Myrtice Dowler", "prodid": 19, "prodname": "Leopardworks" },
        { "custid": 65, "custname": "Myrtice Dowler", "prodid": 36, "prodname": "Tulipnite" },
        { "custid": 65, "custname": "Myrtice Dowler", "prodid": 33, "prodname": "Questindustries" },
        { "custid": 65, "custname": "Myrtice Dowler", "prodid": 28, "prodname": "Pluto Foods" },
        { "custid": 66, "custname": "Nickie Siegle", "prodid": 10, "prodname": "Forestway" },
        { "custid": 66, "custname": "Nickie Siegle", "prodid": 21, "prodname": "Mazecurity" },
        { "custid": 67, "custname": "Nidia Jeter", "prodid": 26, "prodname": "Oysterwood" },
        { "custid": 67, "custname": "Nidia Jeter", "prodid": 16, "prodname": "Hammermobile" },
        { "custid": 67, "custname": "Nidia Jeter", "prodid": 6, "prodname": "Cliffway" },
        { "custid": 67, "custname": "Nidia Jeter", "prodid": 35, "prodname": "Smartland" },
        { "custid": 67, "custname": "Nidia Jeter", "prodid": 8, "prodname": "Electrorks" },
        { "custid": 67, "custname": "Nidia Jeter", "prodid": 34, "prodname": "Sharkfin Entertainment" },
        { "custid": 67, "custname": "Nidia Jeter", "prodid": 12, "prodname": "Gale" },
        { "custid": 67, "custname": "Nidia Jeter", "prodid": 40, "prodname": "Witchystems" },
        { "custid": 67, "custname": "Nidia Jeter", "prodid": 29, "prodname": "Pride Systems" },
        { "custid": 68, "custname": "Nubia Voges", "prodid": 19, "prodname": "Leopardworks" },
        { "custid": 68, "custname": "Nubia Voges", "prodid": 6, "prodname": "Cliffway" },
        { "custid": 68, "custname": "Nubia Voges", "prodid": 8, "prodname": "Electrorks" },
        { "custid": 69, "custname": "Octavia Cabello", "prodid": 35, "prodname": "Smartland" },
        { "custid": 69, "custname": "Octavia Cabello", "prodid": 24, "prodname": "Nimbletainment" },
        { "custid": 69, "custname": "Octavia Cabello", "prodid": 23, "prodname": "Moonlight Technologies" },
        { "custid": 69, "custname": "Octavia Cabello", "prodid": 11, "prodname": "Frostfire Navigations" },
        { "custid": 69, "custname": "Octavia Cabello", "prodid": 3, "prodname": "Cavestones" },
        { "custid": 69, "custname": "Octavia Cabello", "prodid": 30, "prodname": "Priductions" },
        { "custid": 69, "custname": "Octavia Cabello", "prodid": 22, "prodname": "Mercury Coms" },
        { "custid": 70, "custname": "Pablo Forgey", "prodid": 9, "prodname": "Enigmotors" },
        { "custid": 70, "custname": "Pablo Forgey", "prodid": 2, "prodname": "Auragate" },
        { "custid": 70, "custname": "Pablo Forgey", "prodid": 13, "prodname": "Gnomehead" },
        { "custid": 70, "custname": "Pablo Forgey", "prodid": 37, "prodname": "Tundracoustics" },
        { "custid": 70, "custname": "Pablo Forgey", "prodid": 14, "prodname": "Gorillaworld" },
        { "custid": 71, "custname": "Patrica Whittier", "prodid": 30, "prodname": "Priductions" },
        { "custid": 71, "custname": "Patrica Whittier", "prodid": 9, "prodname": "Enigmotors" },
        { "custid": 71, "custname": "Patrica Whittier", "prodid": 25, "prodname": "Oakbridge" },
        { "custid": 71, "custname": "Patrica Whittier", "prodid": 15, "prodname": "Grottoair" },
        { "custid": 72, "custname": "Pearlie Sowell", "prodid": 14, "prodname": "Gorillaworld" },
        { "custid": 72, "custname": "Pearlie Sowell", "prodid": 26, "prodname": "Oysterwood" },
        { "custid": 72, "custname": "Pearlie Sowell", "prodid": 3, "prodname": "Cavestones" },
        { "custid": 72, "custname": "Pearlie Sowell", "prodid": 39, "prodname": "Wavigations" },
        { "custid": 72, "custname": "Pearlie Sowell", "prodid": 38, "prodname": "Twister" },
        { "custid": 72, "custname": "Pearlie Sowell", "prodid": 28, "prodname": "Pluto Foods" },
        { "custid": 72, "custname": "Pearlie Sowell", "prodid": 34, "prodname": "Sharkfin Entertainment" },
        { "custid": 73, "custname": "Pearline Saracino", "prodid": 24, "prodname": "Nimbletainment" },
        { "custid": 73, "custname": "Pearline Saracino", "prodid": 40, "prodname": "Witchystems" },
        { "custid": 73, "custname": "Pearline Saracino", "prodid": 26, "prodname": "Oysterwood" },
        { "custid": 73, "custname": "Pearline Saracino", "prodid": 19, "prodname": "Leopardworks" },
        { "custid": 73, "custname": "Pearline Saracino", "prodid": 3, "prodname": "Cavestones" },
        { "custid": 73, "custname": "Pearline Saracino", "prodid": 6, "prodname": "Cliffway" },
        { "custid": 74, "custname": "Rachelle Sitz", "prodid": 28, "prodname": "Pluto Foods" },
        { "custid": 74, "custname": "Rachelle Sitz", "prodid": 18, "prodname": "Imaginavigations" },
        { "custid": 74, "custname": "Rachelle Sitz", "prodid": 12, "prodname": "Gale" },
        { "custid": 74, "custname": "Rachelle Sitz", "prodid": 34, "prodname": "Sharkfin Entertainment" },
        { "custid": 74, "custname": "Rachelle Sitz", "prodid": 7, "prodname": "Cruxolutions" },
        { "custid": 74, "custname": "Rachelle Sitz", "prodid": 2, "prodname": "Auragate" },
        { "custid": 74, "custname": "Rachelle Sitz", "prodid": 24, "prodname": "Nimbletainment" },
        { "custid": 74, "custname": "Rachelle Sitz", "prodid": 29, "prodname": "Pride Systems" },
        { "custid": 75, "custname": "Ramiro Isreal", "prodid": 19, "prodname": "Leopardworks" },
        { "custid": 75, "custname": "Ramiro Isreal", "prodid": 26, "prodname": "Oysterwood" },
        { "custid": 75, "custname": "Ramiro Isreal", "prodid": 11, "prodname": "Frostfire Navigations" },
        { "custid": 75, "custname": "Ramiro Isreal", "prodid": 9, "prodname": "Enigmotors" },
        { "custid": 75, "custname": "Ramiro Isreal", "prodid": 5, "prodname": "Cliffoods" },
        { "custid": 75, "custname": "Ramiro Isreal", "prodid": 23, "prodname": "Moonlight Technologies" },
        { "custid": 76, "custname": "Randal Pipes", "prodid": 34, "prodname": "Sharkfin Entertainment" },
        { "custid": 76, "custname": "Randal Pipes", "prodid": 23, "prodname": "Moonlight Technologies" },
        { "custid": 76, "custname": "Randal Pipes", "prodid": 37, "prodname": "Tundracoustics" },
        { "custid": 76, "custname": "Randal Pipes", "prodid": 18, "prodname": "Imaginavigations" },
        { "custid": 77, "custname": "Reyes Wile", "prodid": 18, "prodname": "Imaginavigations" },
        { "custid": 77, "custname": "Reyes Wile", "prodid": 20, "prodname": "Mars Corporation" },
        { "custid": 77, "custname": "Reyes Wile", "prodid": 31, "prodname": "Pumpkin Microsystems" },
        { "custid": 77, "custname": "Reyes Wile", "prodid": 7, "prodname": "Cruxolutions" },
        { "custid": 77, "custname": "Reyes Wile", "prodid": 21, "prodname": "Mazecurity" },
        { "custid": 77, "custname": "Reyes Wile", "prodid": 15, "prodname": "Grottoair" },
        { "custid": 77, "custname": "Reyes Wile", "prodid": 39, "prodname": "Wavigations" },
        { "custid": 77, "custname": "Reyes Wile", "prodid": 32, "prodname": "Questindustries" },
        { "custid": 78, "custname": "Rima Cromer", "prodid": 12, "prodname": "Gale" },
        { "custid": 78, "custname": "Rima Cromer", "prodid": 16, "prodname": "Hammermobile" },
        { "custid": 78, "custname": "Rima Cromer", "prodid": 5, "prodname": "Cliffoods" },
        { "custid": 79, "custname": "Rosalina Vallance", "prodid": 6, "prodname": "Cliffway" },
        { "custid": 79, "custname": "Rosalina Vallance", "prodid": 9, "prodname": "Enigmotors" },
        { "custid": 79, "custname": "Rosalina Vallance", "prodid": 27, "prodname": "Peach Aviation" },
        { "custid": 80, "custname": "Roscoe Castaneda", "prodid": 1, "prodname": "Apache Records" },
        { "custid": 80, "custname": "Roscoe Castaneda", "prodid": 12, "prodname": "Gale" },
        { "custid": 80, "custname": "Roscoe Castaneda", "prodid": 29, "prodname": "Pride Systems" },
        { "custid": 80, "custname": "Roscoe Castaneda", "prodid": 5, "prodname": "Cliffoods" },
        { "custid": 81, "custname": "Rossana Kerman", "prodid": 4, "prodname": "Cavologies" },
        { "custid": 82, "custname": "Seth Songer", "prodid": 30, "prodname": "Priductions" },
        { "custid": 82, "custname": "Seth Songer", "prodid": 40, "prodname": "Witchystems" },
        { "custid": 82, "custname": "Seth Songer", "prodid": 27, "prodname": "Peach Aviation" },
        { "custid": 82, "custname": "Seth Songer", "prodid": 16, "prodname": "Hammermobile" },
        { "custid": 82, "custname": "Seth Songer", "prodid": 26, "prodname": "Oysterwood" },
        { "custid": 82, "custname": "Seth Songer", "prodid": 4, "prodname": "Cavologies" },
        { "custid": 82, "custname": "Seth Songer", "prodid": 6, "prodname": "Cliffway" },
        { "custid": 82, "custname": "Seth Songer", "prodid": 9, "prodname": "Enigmotors" },
        { "custid": 82, "custname": "Seth Songer", "prodid": 33, "prodname": "Questindustries" },
        { "custid": 83, "custname": "Shad Kemper", "prodid": 26, "prodname": "Oysterwood" },
        { "custid": 83, "custname": "Shad Kemper", "prodid": 2, "prodname": "Auragate" },
        { "custid": 83, "custname": "Shad Kemper", "prodid": 14, "prodname": "Gorillaworld" },
        { "custid": 83, "custname": "Shad Kemper", "prodid": 12, "prodname": "Gale" },
        { "custid": 83, "custname": "Shad Kemper", "prodid": 5, "prodname": "Cliffoods" },
        { "custid": 83, "custname": "Shad Kemper", "prodid": 11, "prodname": "Frostfire Navigations" },
        { "custid": 84, "custname": "Shala Marotta", "prodid": 29, "prodname": "Pride Systems" },
        { "custid": 84, "custname": "Shala Marotta", "prodid": 23, "prodname": "Moonlight Technologies" },
        { "custid": 84, "custname": "Shala Marotta", "prodid": 30, "prodname": "Priductions" },
        { "custid": 84, "custname": "Shala Marotta", "prodid": 19, "prodname": "Leopardworks" },
        { "custid": 84, "custname": "Shala Marotta", "prodid": 1, "prodname": "Apache Records" },
        { "custid": 84, "custname": "Shala Marotta", "prodid": 4, "prodname": "Cavologies" },
        { "custid": 85, "custname": "Shanelle Riggin", "prodid": 14, "prodname": "Gorillaworld" },
        { "custid": 85, "custname": "Shanelle Riggin", "prodid": 9, "prodname": "Enigmotors" },
        { "custid": 85, "custname": "Shanelle Riggin", "prodid": 13, "prodname": "Gnomehead" },
        { "custid": 85, "custname": "Shanelle Riggin", "prodid": 18, "prodname": "Imaginavigations" },
        { "custid": 85, "custname": "Shanelle Riggin", "prodid": 22, "prodname": "Mercury Coms" },
        { "custid": 85, "custname": "Shanelle Riggin", "prodid": 30, "prodname": "Priductions" },
        { "custid": 85, "custname": "Shanelle Riggin", "prodid": 28, "prodname": "Pluto Foods" },
        { "custid": 86, "custname": "Shantay Braga", "prodid": 27, "prodname": "Peach Aviation" },
        { "custid": 86, "custname": "Shantay Braga", "prodid": 28, "prodname": "Pluto Foods" },
        { "custid": 86, "custname": "Shantay Braga", "prodid": 36, "prodname": "Tulipnite" },
        { "custid": 86, "custname": "Shantay Braga", "prodid": 37, "prodname": "Tundracoustics" },
        { "custid": 86, "custname": "Shantay Braga", "prodid": 33, "prodname": "Questindustries" },
        { "custid": 87, "custname": "Shawanda Cayetano", "prodid": 9, "prodname": "Enigmotors" },
        { "custid": 87, "custname": "Shawanda Cayetano", "prodid": 30, "prodname": "Priductions" },
        { "custid": 87, "custname": "Shawanda Cayetano", "prodid": 36, "prodname": "Tulipnite" },
        { "custid": 87, "custname": "Shawanda Cayetano", "prodid": 1, "prodname": "Apache Records" },
        { "custid": 87, "custname": "Shawanda Cayetano", "prodid": 26, "prodname": "Oysterwood" },
        { "custid": 87, "custname": "Shawanda Cayetano", "prodid": 27, "prodname": "Peach Aviation" },
        { "custid": 88, "custname": "Shela Jacinto", "prodid": 34, "prodname": "Sharkfin Entertainment" },
        { "custid": 88, "custname": "Shela Jacinto", "prodid": 29, "prodname": "Pride Systems" },
        { "custid": 89, "custname": "Shirl Bischof", "prodid": 14, "prodname": "Gorillaworld" },
        { "custid": 89, "custname": "Shirl Bischof", "prodid": 38, "prodname": "Twister" },
        { "custid": 89, "custname": "Shirl Bischof", "prodid": 28, "prodname": "Pluto Foods" },
        { "custid": 90, "custname": "Sulema Restivo", "prodid": 2, "prodname": "Auragate" },
        { "custid": 90, "custname": "Sulema Restivo", "prodid": 17, "prodname": "Hurricanetworks" },
        { "custid": 90, "custname": "Sulema Restivo", "prodid": 7, "prodname": "Cruxolutions" },
        { "custid": 90, "custname": "Sulema Restivo", "prodid": 1, "prodname": "Apache Records" },
        { "custid": 90, "custname": "Sulema Restivo", "prodid": 23, "prodname": "Moonlight Technologies" },
        { "custid": 90, "custname": "Sulema Restivo", "prodid": 15, "prodname": "Grottoair" },
        { "custid": 91, "custname": "Sylvia Ellard", "prodid": 30, "prodname": "Priductions" },
        { "custid": 91, "custname": "Sylvia Ellard", "prodid": 24, "prodname": "Nimbletainment" },
        { "custid": 91, "custname": "Sylvia Ellard", "prodid": 25, "prodname": "Oakbridge" },
        { "custid": 91, "custname": "Sylvia Ellard", "prodid": 1, "prodname": "Apache Records" },
        { "custid": 91, "custname": "Sylvia Ellard", "prodid": 11, "prodname": "Frostfire Navigations" },
        { "custid": 91, "custname": "Sylvia Ellard", "prodid": 22, "prodname": "Mercury Coms" },
        { "custid": 92, "custname": "Tequila Bondy", "prodid": 34, "prodname": "Sharkfin Entertainment" },
        { "custid": 92, "custname": "Tequila Bondy", "prodid": 13, "prodname": "Gnomehead" },
        { "custid": 93, "custname": "Theresa Reichenbach", "prodid": 29, "prodname": "Pride Systems" },
        { "custid": 93, "custname": "Theresa Reichenbach", "prodid": 6, "prodname": "Cliffway" },
        { "custid": 93, "custname": "Theresa Reichenbach", "prodid": 19, "prodname": "Leopardworks" },
        { "custid": 93, "custname": "Theresa Reichenbach", "prodid": 2, "prodname": "Auragate" },
        { "custid": 93, "custname": "Theresa Reichenbach", "prodid": 30, "prodname": "Priductions" },
        { "custid": 93, "custname": "Theresa Reichenbach", "prodid": 16, "prodname": "Hammermobile" },
        { "custid": 93, "custname": "Theresa Reichenbach", "prodid": 31, "prodname": "Pumpkin Microsystems" },
        { "custid": 94, "custname": "Treva Pankow", "prodid": 25, "prodname": "Oakbridge" },
        { "custid": 94, "custname": "Treva Pankow", "prodid": 13, "prodname": "Gnomehead" },
        { "custid": 94, "custname": "Treva Pankow", "prodid": 11, "prodname": "Frostfire Navigations" },
        { "custid": 94, "custname": "Treva Pankow", "prodid": 17, "prodname": "Hurricanetworks" },
        { "custid": 94, "custname": "Treva Pankow", "prodid": 14, "prodname": "Gorillaworld" },
        { "custid": 94, "custname": "Treva Pankow", "prodid": 2, "prodname": "Auragate" },
        { "custid": 94, "custname": "Treva Pankow", "prodid": 20, "prodname": "Mars Corporation" },
        { "custid": 94, "custname": "Treva Pankow", "prodid": 39, "prodname": "Wavigations" },
        { "custid": 94, "custname": "Treva Pankow", "prodid": 28, "prodname": "Pluto Foods" },
        { "custid": 95, "custname": "Vena Brundidge", "prodid": 13, "prodname": "Gnomehead" },
        { "custid": 95, "custname": "Vena Brundidge", "prodid": 9, "prodname": "Enigmotors" },
        { "custid": 95, "custname": "Vena Brundidge", "prodid": 3, "prodname": "Cavestones" },
        { "custid": 95, "custname": "Vena Brundidge", "prodid": 19, "prodname": "Leopardworks" },
        { "custid": 95, "custname": "Vena Brundidge", "prodid": 40, "prodname": "Witchystems" },
        { "custid": 95, "custname": "Vena Brundidge", "prodid": 33, "prodname": "Questindustries" },
        { "custid": 95, "custname": "Vena Brundidge", "prodid": 34, "prodname": "Sharkfin Entertainment" },
        { "custid": 95, "custname": "Vena Brundidge", "prodid": 29, "prodname": "Pride Systems" },
        { "custid": 96, "custname": "Vera Northup", "prodid": 1, "prodname": "Apache Records" },
        { "custid": 96, "custname": "Vera Northup", "prodid": 34, "prodname": "Sharkfin Entertainment" },
        { "custid": 96, "custname": "Vera Northup", "prodid": 9, "prodname": "Enigmotors" },
        { "custid": 96, "custname": "Vera Northup", "prodid": 29, "prodname": "Pride Systems" },
        { "custid": 96, "custname": "Vera Northup", "prodid": 8, "prodname": "Electrorks" },
        { "custid": 96, "custname": "Vera Northup", "prodid": 18, "prodname": "Imaginavigations" },
        { "custid": 96, "custname": "Vera Northup", "prodid": 38, "prodname": "Twister" },
        { "custid": 96, "custname": "Vera Northup", "prodid": 23, "prodname": "Moonlight Technologies" },
        { "custid": 97, "custname": "Wanita Ruzicka", "prodid": 3, "prodname": "Cavestones" },
        { "custid": 97, "custname": "Wanita Ruzicka", "prodid": 9, "prodname": "Enigmotors" },
        { "custid": 97, "custname": "Wanita Ruzicka", "prodid": 13, "prodname": "Gnomehead" },
        { "custid": 97, "custname": "Wanita Ruzicka", "prodid": 16, "prodname": "Hammermobile" },
        { "custid": 97, "custname": "Wanita Ruzicka", "prodid": 1, "prodname": "Apache Records" },
        { "custid": 97, "custname": "Wanita Ruzicka", "prodid": 11, "prodname": "Frostfire Navigations" },
        { "custid": 97, "custname": "Wanita Ruzicka", "prodid": 35, "prodname": "Smartland" },
        { "custid": 97, "custname": "Wanita Ruzicka", "prodid": 2, "prodname": "Auragate" },
        { "custid": 97, "custname": "Wanita Ruzicka", "prodid": 34, "prodname": "Sharkfin Entertainment" },
        { "custid": 98, "custname": "Willie Manriquez", "prodid": 39, "prodname": "Wavigations" },
        { "custid": 98, "custname": "Willie Manriquez", "prodid": 33, "prodname": "Questindustries" },
        { "custid": 98, "custname": "Willie Manriquez", "prodid": 8, "prodname": "Electrorks" },
        { "custid": 99, "custname": "Windy Lossett", "prodid": 32, "prodname": "Questindustries" },
        { "custid": 99, "custname": "Windy Lossett", "prodid": 2, "prodname": "Auragate" },
        { "custid": 99, "custname": "Windy Lossett", "prodid": 9, "prodname": "Enigmotors" },
        { "custid": 99, "custname": "Windy Lossett", "prodid": 18, "prodname": "Imaginavigations" },
        { "custid": 99, "custname": "Windy Lossett", "prodid": 17, "prodname": "Hurricanetworks" },
        { "custid": 99, "custname": "Windy Lossett", "prodid": 26, "prodname": "Oysterwood" },
        { "custid": 99, "custname": "Windy Lossett", "prodid": 40, "prodname": "Witchystems" },
        { "custid": 99, "custname": "Windy Lossett", "prodid": 23, "prodname": "Moonlight Technologies" },
        { "custid": 100, "custname": "Yajaira Mazur", "prodid": 30, "prodname": "Priductions" },
        { "custid": 100, "custname": "Yajaira Mazur", "prodid": 9, "prodname": "Enigmotors" },
        { "custid": 100, "custname": "Yajaira Mazur", "prodid": 24, "prodname": "Nimbletainment" },
        { "custid": 100, "custname": "Yajaira Mazur", "prodid": 39, "prodname": "Wavigations" },
        { "custid": 100, "custname": "Yajaira Mazur", "prodid": 6, "prodname": "Cliffway" },
        { "custid": 100, "custname": "Yajaira Mazur", "prodid": 19, "prodname": "Leopardworks" },
        { "custid": 100, "custname": "Yajaira Mazur", "prodid": 10, "prodname": "Forestway" },
        { "custid": -1, "custname": "~", "prodid": 1, "prodname": "Apache Records" },
        { "custid": -1, "custname": "~", "prodid": 2, "prodname": "Auragate" },
        { "custid": -1, "custname": "~", "prodid": 3, "prodname": "Cavestones" },
        { "custid": -1, "custname": "~", "prodid": 4, "prodname": "Cavologies" },
        { "custid": -1, "custname": "~", "prodid": 5, "prodname": "Cliffoods" },
        { "custid": -1, "custname": "~", "prodid": 6, "prodname": "Cliffway" },
        { "custid": -1, "custname": "~", "prodid": 7, "prodname": "Cruxolutions" },
        { "custid": -1, "custname": "~", "prodid": 8, "prodname": "Electrorks" },
        { "custid": -1, "custname": "~", "prodid": 9, "prodname": "Enigmotors" },
        { "custid": -1, "custname": "~", "prodid": 10, "prodname": "Forestway" },
        { "custid": -1, "custname": "~", "prodid": 11, "prodname": "Frostfire Navigations" },
        { "custid": -1, "custname": "~", "prodid": 12, "prodname": "Gale" },
        { "custid": -1, "custname": "~", "prodid": 13, "prodname": "Gnomehead" },
        { "custid": -1, "custname": "~", "prodid": 14, "prodname": "Gorillaworld" },
        { "custid": -1, "custname": "~", "prodid": 15, "prodname": "Grottoair" },
        { "custid": -1, "custname": "~", "prodid": 16, "prodname": "Hammermobile" },
        { "custid": -1, "custname": "~", "prodid": 17, "prodname": "Hurricanetworks" },
        { "custid": -1, "custname": "~", "prodid": 18, "prodname": "Imaginavigations" },
        { "custid": -1, "custname": "~", "prodid": 19, "prodname": "Leopardworks" },
        { "custid": -1, "custname": "~", "prodid": 20, "prodname": "Mars Corporation" },
        { "custid": -1, "custname": "~", "prodid": 21, "prodname": "Mazecurity" },
        { "custid": -1, "custname": "~", "prodid": 22, "prodname": "Mercury Coms" },
        { "custid": -1, "custname": "~", "prodid": 23, "prodname": "Moonlight Technologies" },
        { "custid": -1, "custname": "~", "prodid": 24, "prodname": "Nimbletainment" },
        { "custid": -1, "custname": "~", "prodid": 25, "prodname": "Oakbridge" },
        { "custid": -1, "custname": "~", "prodid": 26, "prodname": "Oysterwood" },
        { "custid": -1, "custname": "~", "prodid": 27, "prodname": "Peach Aviation" },
        { "custid": -1, "custname": "~", "prodid": 28, "prodname": "Pluto Foods" },
        { "custid": -1, "custname": "~", "prodid": 29, "prodname": "Pride Systems" },
        { "custid": -1, "custname": "~", "prodid": 30, "prodname": "Priductions" },
        { "custid": -1, "custname": "~", "prodid": 31, "prodname": "Pumpkin Microsystems" },
        { "custid": -1, "custname": "~", "prodid": 32, "prodname": "Questindustries" },
        { "custid": -1, "custname": "~", "prodid": 33, "prodname": "Questindustries" },
        { "custid": -1, "custname": "~", "prodid": 34, "prodname": "Sharkfin Entertainment" },
        { "custid": -1, "custname": "~", "prodid": 35, "prodname": "Smartland" },
        { "custid": -1, "custname": "~", "prodid": 36, "prodname": "Tulipnite" },
        { "custid": -1, "custname": "~", "prodid": 37, "prodname": "Tundracoustics" },
        { "custid": -1, "custname": "~", "prodid": 38, "prodname": "Twister" },
        { "custid": -1, "custname": "~", "prodid": 39, "prodname": "Wavigations" },
        { "custid": -1, "custname": "~", "prodid": 40, "prodname": "Witchystems" }
    ];

    srcCust: MatTableDataSource<cusData>;
    srcProd: MatTableDataSource<prdData>;
    custColumns: string[] = [];
    prodColumns: string[] = [];
    cusSelection = new SelectionModel<cusData>(false, []);
    prdSelection = new SelectionModel<prdData>(true, []);

    constructor() {
        this.custColumns = ['name', 'select'];
        this.prodColumns = ['select', 'name'];
        this.srcCust = new MatTableDataSource(this.customers);
        this.srcProd = new MatTableDataSource(this.products);
    }

    ngOnInit() {
    }

    ngAfterViewInit() {
        this.srcCust.paginator = this.cusPaginator;
        this.srcProd.paginator = this.prdPaginator;
    }

    applyFilter(filterValue: string) {
        this.srcCust.filter = filterValue.trim().toLowerCase();

        // this.dataSource.filter=-1;
        if (this.srcProd.paginator) {
            this.srcProd.paginator.firstPage();
        }
    }

    custChecked(event, row) {
        event ? this.cusSelection.toggle(row) : null;
        this.prdSelection.clear();
        this.products.filter(el => { return row.products.find(pr => { return (pr === el.id) }); }).forEach(el => this.prdSelection.select(el));
        this.products.sort((a, b) => (!this.prdSelection.isSelected(a) && this.prdSelection.isSelected(b)) ? 1 : (this.prdSelection.isSelected(a) && !this.prdSelection.isSelected(b)) ? -1 : 0)
        this.prdPaginator._changePageSize(this.prdPaginator.pageSize); // An ugly way to do a table refresh
    }

    /** Whether the number of selected elements matches the total number of rows. */
    isAllSelected() {
        const numSelected = this.prdSelection.selected.length;
        const numRows = this.srcProd.data.length;
        return numSelected === numRows;
    }

    /** Selects all rows if they are not all selected; otherwise clear selection. */
    masterToggle() {
        this.isAllSelected() ?
            this.prdSelection.clear() :
            this.srcProd.data.forEach(row => this.prdSelection.select(row));
    }

    pageChanged(){
        console.log('page changed')
        this.cusSelection.clear();
        this.prdSelection.clear();
    }
}
